version: '3.8'

services:
  bedrock-access-gateway:
    image: ghcr.io/aaronbolton/bedrock-access-gateway:latest
    build:
      context: ./src
      dockerfile: Dockerfile_ecs
    ports:
      - "80:80"
    environment:
      - ENV_VAR_NAME=env_var_value