services:
  bedrock-access-gateway:
    image: ghcr.io/aaronbolton/bedrock-access-gateway:latest
    build:
      context: ./src
      dockerfile: Dockerfile_ecs
    ports:
      - "80:80"
    environment:
      - DEFAULT_API_KEYS=bedrock